// new Promise((resolve, reject) => {

//   throw new Error("Ошибка!");

// })

// try {
//   setInterval(() => {throw new Error('Хрень ошибка')}, 1000);
// } catch (e) {
//   console.log(e);
// }